### ISSUE TITLE
consul template does not read upstream server info

### ISSUE THREAD

**Issue by olliejm** [botleg/blue-green#2]
I've been trying to get this image to work as a blue-green deployment option for my own image for a while now, but visiting the endpoints of either of my services always ends up in '502 bad gateway'.

The only culprit I can seem to find is the lines:

`{{range service $blue}}` and
`{{range service $green}}

Do not seem to be inserting server data into the generated nginx conf, as running 

`docker exec bg cat /etc/nginx/nginx.conf` 

Shows the upstream blocks to contain only the `127.0.0.1:55000` default address.

The images are a node server which runs on port 80 - I have also tried other ports with no luck.

Output from `docker-machine ls` prior to running compose is as-expected, so the swarm is correctly configured as far as I can tell.

If you could offer any assistance regarding what the problem might be it would be greatly appreciated.

**Comment by olliejm** [comment]
I've tried running it with the hanzel/nginx-html images also, and `nginx.conf` in that case returns the following:

```nginx
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
```

**Comment by olliejm** [comment]
It seems to be working with my own images now - I am not sure exactly what the problem was, only thing I can think of is possibly I built one of the images within `docker env master` or `docker env slave` rather than `docker env -swarm master`

**Comment by hanzeljesheen** [comment]
@olliejm that should've been the problem. glad to know that it's working fine now.
